import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const wasmDir = resolve(root, "wasm");
const builtWasmPath = resolve(wasmDir, "zig-out/bin/restty.wasm");
const embeddedWasmPath = resolve(root, "src/wasm/embedded.ts");
const wasmOptimizeMode = process.env.RESTTY_WASM_OPTIMIZE?.trim() || "ReleaseSafe";

function runCommand(command: string[], cwd: string): void {
  const proc = spawnSync(command[0], command.slice(1), {
    cwd,
    stdio: ["ignore", "inherit", "inherit"],
  });

  if (proc.status !== 0) {
    process.exit(proc.status ?? 1);
  }
}

console.log("Building wasm module...");
runCommand(
  ["zig", "build", "-Dtarget=wasm32-freestanding", `-Doptimize=${wasmOptimizeMode}`],
  wasmDir,
);

console.log("Regenerating src/wasm/embedded.ts...");
const bytes = await readFile(builtWasmPath);
const b64 = Buffer.from(bytes).toString("base64");
const wrapped = b64.match(/.{1,120}/g)?.join("\n") ?? b64;
const content =
  "// Auto-generated by build:wasm script.\n" +
  "// Source: wasm/zig-out/bin/restty.wasm\n" +
  `// Zig optimize mode: ${wasmOptimizeMode}\n` +
  `export const WASM_BASE64: string = \`\n${wrapped}\n\`;\n`;
await writeFile(embeddedWasmPath, content, "utf-8");

console.log("WASM build and embed refresh complete.");
